### PR TITLE
Fix stats bugs

### LINKED ISSUE #121: Fix stats view bugs since sessions now store data into db

### PR DESCRIPTION
**Pull request by ZhiHanL**
closes #121

### CODE REVIEW

File: src/lib/utils.ts [hunk 1]
```diff
@@ -78,12 +78,17 @@ export function createSessionData(
   const score = correct.toString() + "/" + count.toString();
   const decksString = decks.join(", ");
   const indexString = index.toString() + ".)";
-  const startDateConverted = +new Date(startDate);
-  const endDateConverted = +new Date(endDate);
-  const dateString = startDateConverted.toString();
+  const duration = (endDate - startDate) / 1000;
+  const date = new Date(startDate);
+  var options = {
```
Comment (algobot76) [inline src/lib/utils.ts:83]: I think `const` is better than `var` here.

File: src/model/query.ts [hunk 2]
```diff
@@ -277,7 +271,12 @@ export async function getSessionScore(
     .query(Q.where("session_id", session.id))
     .fetch()) as Array<SessionCard>;
   const totalCards = sessionCards.length;
-  return sessionCards.map((sc) => sc.is_correct).length / totalCards;
+  let numberCorrect = 0;
+  sessionCards.forEach((c) => {
+    numberCorrect = c.is_correct ? numberCorrect + 1 : numberCorrect;
```
Comment (algobot76) [inline src/model/query.ts:276]: How about `numberCorrect += c.is_correct? 1 : 0`; I think this is more concise.
